// Contenu du fichier data.js
window.MOTS_CLES = {

"COMPLETE THE MISSION - ACCOMPLIR LA MISSION": "Pendant la mise en place, pour chaque unité dotée de CE mot-clé, placez un pion Mission prioritaire (pion Avantage) allié sur le champ de bataille, en territoire contesté. Tant qu'une unité dotée de CE mot-clé se trouve à [RANGE 1] d'un ou plusieurs pions Mission prioritaire alliés, cette unité gagne [D_SURGE] : [BLOCK]. Lorsqu'une unité dotée de CE mot-clé attaque une unité ennemie à [RANGE 1] d'un ou plusieurs pions Mission prioritaire alliés, la réserve d'attaque de l'unité attaquante gagne le mot-clé CRITIQUE 2.",

"NIMBLE - AGILE": "Après qu'une unité dotée de CE mot-clé a défendu contre une attaque, si elle a dépensé au moins un [DODGE] à n'importe quel moment de la séquence d'attaque, elle gagne un [DODGE].",

"STEADY - AGUERRI": "Après qu'une unité dotée de ce mot-clé a effectué, au cours de son activation, une action Se déplacer, elle peut effectuer une action Attaquer gratuite. <br>Pendant cette action Attaquer, elle ne peut ajouter que des armes à distance aux réserves d'attaques.", 

"AID : AFFILIATION/UNIT TYPE - AIDE : AFFILIATION/TYPE D'UNITE": "Chaque fois qu'une unité dotée de CE mot-clé est censée gagner un [AIM], [DODGE] ou [SURGE], une autre unité alliée de l'affiliation ou du type spécifié à [RANGE 2] et en LdV peut gagner ce pion à la place. <br>Dans ce cas, l'unité dotée de CE mot-clé gagne un [SUPPRESSION], si possible.<br><i>Par exemple, Logray gagne 2 [AIM] et 1 [DODGE] au début de son activation, grâce à son amélioration Ingrédients Secrets. Il décide d’utiliser son mot-clé Aide et une unité de Tirailleurs Ewok gagne 1 de ces [AIM], et une unité de Frondeurs Ewok gagne l’autre [AIM]. Logray gagne 1 [SUPPRESSION] pour chaque utilisation de son mot-clé Aide. Au total il gagne donc 2 [SUPPRESSION] et 1 [DODGE] de ses Ingrédients Secrets.</i>", 

"ALLIES OF CONVENIENCE - ALLIES DE CIRCONSTANCE": "Les unités dotées de CE mot-clé peuvent donner des ordres à des unités de mercenaires alliées de n'importe quelle affiliation. <br><br>De plus, lors de la création d'armée, les joueurs peuvent inclure une unité de mercenaires supplémentaire dans leur armée sans prendre en compte son rang si au moins une unité dotée de CE mot-clé est présente. <br>Ils ne peuvent cependant pas inclure plus d'unités d'un rang particulier que ce qui est normalement autorisé.", 

"WEIGHED DOWN - ALOURDISSEMENT": "Tant qu'une unité dotée de CE mot-clé possède un pion Objectif revendiqué, elle ne peut pas utiliser le mot-clé SAUT.", 

"COUNTERPART - ALTER EGO": "Certaines unités sont de fidèles compagnons ou des sbires soumis, et ne se séparent jamais d'une autre unité. Une telle unité sera dotée du mot-clé Alter Ego et la figurine qui la représente sera toujours ajoutée à une autre unité. Cette figurine est un ALTER EGO et possède une carte ALTER EGO. <br>L'unité combinée possède le rang, le type d'unité, la couleur de dé de défense, la valeur de courage, la fenêtre de conversion d'adrénaline et la vitesse indiquées sur la carte Unité. <br>• Il peut arriver qu'une carte Alter Ego soit d'un type d'unité différent uniquement pour s'équiper de cartes Amélioration. <br>• Le Chef d'une unité combinée peut se voir attribuer des blessures s'il s'agit de la seule figurine non-alter ego de l'unité. <br>• Lorsqu'un pion Blessure est censé être attribué à une figurine non-alter ego d'une unité combinée, le joueur contrôlant cette unité peut attribuer ce pion Blessure à une figurine alter ego non vaincue à la place. Ce pion Blessure doit être attribué à une figurine alter ego s'il était censé vaincre la dernière figurine non-alter ego de l'unité. <br>• Les cartes Amélioration sans armes dont une figurine alter ego est équipée peuvent être utilisées par le reste de l'unité, sauf si la figurine alter ego est vaincue. <br>• Les cartes Amélioration comprenant des armes ne peuvent être utilisées que par la figurine qui en est équipée. <br>• Les figurines non-alter ego de l'unité utilisent le seuil de blessure de leur carte Unité ou Amélioration, tandis que les figurines alter ego utilisent le seuil de blessure de la carte Alter Ego. <br>• L'unité combinée est dotée des mots-clés de la carte Unité et de la carte Alter Ego. <br>• Les figurines de l'unité combinée ne peuvent utiliser que les armes qui se trouvent sur leurs cartes respectives. Si une unité combinée gagne une arme grâce à une carte Commandement, seule la figurine non-alter ego peut l'utiliser. <br>• Si la figurine alter ego est vaincue, l'unité perd tout mot-clé, capacité ou effet de la carte Alter Ego.", 

"ARMOR - ARMURE": "Pendant l'étape « Modifier les dés d'attaque » d'une séquence d'attaque, si l'unité en défense est dotée de CE mot-clé, le joueur qui la contrôle peut annuler tous les résultats [HIT] du jet d'attaque en retirant ces dés de la réserve d'attaque.",

"ARMOR X - ARMURE X": "Pendant l'étape « Modifier les dés d'attaque » d'une séquence d'attaque, si l'unité en défense est dotée de CE mot-clé, le défenseur peut annuler jusqu'à X résultats [HIT] en retirant ces dés de la réserve d'attaque.",

"ARSENAL X": "Lors du choix des armes pendant l'étape « Constituer la réserve d'attaque », chaque figurine de l'unité dotée de CE mot-clé peut ajouter X armes à des réserves d'attaque. <br>Chaque arme ou combinaison d'armes peut constituer une nouvelle réserve d'attaque, mais chaque arme ne peut être ajoutée qu'à une réserve d'attaque.", 

"SCALE - ASCENSION": "Lorsqu'une unité dotée de CE mot-clé grimpe, elle peut se déplacer d'une distance verticale de hauteur 2 maximum. <br>Lorsqu'une unité dotée de CE mot-clé effectue un déplacement, elle ne réduit pas sa vitesse maximale lorsqu'elle entre dans un terrain difficile, en sort ou le traverse.", 

"BOLSTER X - ASSISTANCE X": "En tant qu'action de carte, une unité dotée de CE mot-clé peut choisir jusqu'à X unités alliées à [RANGE 2] : elles gagnent un [SURGE] chacune.", 

"ASSOCIATE : UNIT NAME - ASSOCIE : NOM D'UNITE": "Pendant la création d'armée, une unité dotée de CE mot-clé ne compte pas dans le nombre maximal d'unités de son rang pouvant être incluses si une unité portant le nom spécifié est incluse dans la même armée.",

"ATTACK RUN - ATTAQUE IMPETUEUSE": "Au début de son activation, une unité dotée de CE mot-clé peut augmenter ou diminuer sa vitesse maximale de 1 jusqu'à la fin de cette activation.", 

"SELF-DESTRUCT X - AUTODESTRUCTION X (UNITE)": "Une unité ne peut effectuer une action de carte Autodestruction X que si elle a un nombre de pions Blessure supérieur ou égal à la moitié de son seuil de blessure, arrondi au supérieur. <br>Pour chaque unité à [RANGE 1] et en LdV, lancez X dés d'attaque noirs, en résolvant entièrement chaque jet avant de passer à l'unité suivante. <br>L'unité visée subit 1 blessure pour chaque résultat [A_SURGE] et [CRIT] obtenu, puis elle gagne 1 [SUPPRESSION] pour chaque résultat [HIT] obtenu. <br>Une fois que tous les jets sont résolus, l'unité ayant utilisé l'action de carte est vaincue.",
 
"INDEPENDANT : TOKEN X/ACTION - AUTONOME : PION X/ACTION": "Au début de la Phase d'Activation, si une unité dotée de CE mot-clé ne possède pas de pion Ordre, cette unité peut gagner X pions spécifiés ou effectuer l'action spécifiée en tant qu'action gratuite.",

"BARRAGE": "Une unité dotée de CE mot-clé peut effectuer deux actions Attaquer au lieu d'une si elle n'utilise pas le mot-clé Arsenal au cours de son activation.", 

"WOUND X - BLESSURE X": "La première fois qu'une unité dotée de CE mot-clé entre en jeu, cette unité subit X blessures.", 

"BLOCK - BLOCAGE": "Lorsqu'une unité dotée de CE mot-clé défend, si elle dépense un ou plusieurs [DODGE] au cours de l'étape « Appliquer les esquives et couverts », elle gagne [D_SURGE] : [BLOCK].", 

"SHIELDED X - BOUCLIER X": "Une unité dotée de CE mot-clé possède X pions Bouclier. Les pions Bouclier appartiennent à l'unité et ne sont pas attribués individuellement à des figurines. <br>Si une unité gagne le mot-clé Bouclier X, elle gagne X pions Bouclier. <br>De même, si une unité perd le mot-clé Bouclier X, elle perd X pions Bouclier. <br>Les pions Bouclier sont recto verso : un côté actif et un côté inactif. Ils entrent toujours en jeu côté actif visible. Lorsqu’une unité retourne un pion Bouclier actif, ce pion devient inactif (le côté inactif du pion est désormais visible). Lorsqu’une unité retourne un pion Bouclier inactif, ce pion devient actif (le côté actif du pion est désormais visible). <br>Tant qu'elle défend contre une attaque à distance, pendant l'étape « Modifier les dés d'attaque », une unité en défense peut retourner n'importe quel nombre de ses pions Bouclier actifs sur leur côté inactif afin d'annuler un résultat [HIT] ou [CRIT] par pion Bouclier ainsi retourné.", 

"CACHE": "Pendant la mise en place, une unité équipée d'une carte Amélioration dotée de CE mot-clé place le ou les pions indiqués sur la carte où figure le mot-clé Cache. L’unité peut dépenser ces pions, même si une ou plusieurs des figurines ajoutées à l'unité grâce à cette carte sont vaincues.", 

"CALCUL ODDS - CALCUL DE PROBABILITES": "En tant qu'action de carte, une unité dotée de CE mot-clé peut choisir une unité de soldats alliée à [RANGE 2] et en LdV : cette dernière gagne un [AIM], un [DODGE] et un [SUPPRESSION].", 

"CHARGE": "Après qu'une unité dotée de CE mot-clé a effectué, au cours de son activation, une action Se déplacer qui l'amène au contact d'une figurine ennemie afin d'attaquer au corps-à-corps, cette unité peut effectuer une action Attaquer gratuite contre cette unité en n'utilisant que des armes de corps-à-corps.", 

"JEDI HUNTER - CHASSEUR DE JEDI": "Lorsqu'une unité dotée de CE mot-clé attaque une unité dont la barre d'amélioration affiche une icône d’amélioration [FORCE], elle gagne [A_SURGE] : [HIT].",

"ADVANCED TARGETING : UNIT TYPE X - CIBLAGE AVANCE : TYPE D'UNITE X": "Lorsqu'une unité dotée de CE mot-clé effectue une attaque contre une unité ennemie du type spécifié, pendant l'étape « Constituer la réserve d'attaque », elle peut gagner X [AIM]. <br>Une unité qui utilise CE mot-clé ne peut constituer qu'une réserve d'attaque et saute l'étape « Déclarer un défenseur supplémentaire » de la séquence d'attaque.", 

"TARGET X - CIBLE X": "Après qu'une unité dotée de CE mot-clé a reçu un ordre, elle gagne X [AIM].", 

"FIELD COMMANDER - COMMANDANT DES OPÉRATIONS": "Pendant la création d'armée, une armée incluant une unité dotée de CE mot-clé peut ignorer le nombre minimal de rangs [COMMANDANT] autorisés. <br>Si l'armée d'un joueur ne contient pas d'unité [COMMANDANT] pendant la mise en place, mais qu'elle contient une unité dotée de CE mot-clé, cette unité gagne un pion Commandant. <br>Lorsqu'un joueur révèle une carte Commandement non spécifique à [COMMANDANT] ou [AGENT], il peut nommer une unité alliée dotée de CE mot-clé comme Commandant, lui permettant ainsi de donner des ordres. <br>Une unité dotée de CE mot-clé n'est pas un [COMMANDANT] et n'est considérée comme tel que pour donner des ordres avec une carte Commandement au cours de la Phase de Commandement.<br>Une unité dotée de CE mot-clé est considérée comme un [COMMANDANT] de cette faction ou affiliation lorsque vous créez votre main de commandement. <br>De plus, si une unité alliée se trouve à [RANGE 3] de l'unité possédant le pion Commandement et que les deux unités appartiennent à la même faction ou affiliation, cette unité alliée peut considérer que l’unité dotée de CE mot-clé est une unité [COMMANDANT] ayant une valeur de COURAGE de 2.",
 
"GUIDANCE - CONSEILS : TYPE D'UNITE": "Lorsqu'une unité utilise l'action de carte Conseils, choisissez une autre unité alliée du type spécifié et située à [RANGE 2]. L'unité choisie effectue une action gratuite autre qu'Attaquer.", 

"COMPEL : RANK/UNIT TYPE - CONTRAINTE : RANG/TYPE D'UNITE": "Après qu'une autre unité de soldats non-droïdes alliée correspondant au rang ou type indiqué située à [RANGE 2] d'une unité alliée dotée de CE mot-clé a effectué son étape « Se rallier », si elle est démoralisée mais pas paniquée, au début de son étape « Effectuer des actions », elle peut gagner un [SUPPRESSION] pour effectuer une action Se déplacer gratuite.", 

"COORDINATE : UNITE NAME/UNIT TYPE - COORDINATION : NOM/TYPE D'UNITE": "Après qu'une unité dotée de CE mot-clé a reçu un ordre, elle peut donner un ordre à une unité alliée à [RANGE 1] qui porte le nom ou est du type spécifié. <br>Une unité pour laquelle sont spécifiés plusieurs noms ou types d'unités ne peut donner un ordre qu'à une seule de ces unités en utilisant CE mot-clé. <br>Si une unité déjà dotée de CE mot-clé gagne ce mot-clé une seconde fois, cette unité peut choisir à quelles cibles elle donne un ordre parmi les unités spécifiées sur les deux mots-clés : elle ne donne pas deux ordres.", 

"UNCANNY LUCK X - COUP DE CHANCE X": "Tant qu'une unité dotée de CE mot-clé défend contre une attaque, elle peut relancer jusqu'à X de ses dés de défense au cours de l'étape « Relancer les dés de défense ». Tous les dés relancés grâce à CE mot-clé doivent l'être en même temps, et chaque dé ne peut pas être relancé plus d'une fois.", 

"COVER X - COUVERT X": "Une unité dotée de CE mot-clé qui défend contre une attaque comportant au moins une arme à distance améliore, pendant l'étape « Appliquer les esquives et couverts », la valeur numérique de son couvert d'un nombre égal à X.", 

"DEFEND X - DEFENSE X": "Après qu'une unité dotée de CE mot-clé a reçu un ordre, elle gagne X [DODGE].", 

"DEFLECT - DEFLEXION": "Tant qu'une unité dotée de CE mot-clé défend contre une attaque à distance ou utilise le mot-clé Gardien X, sa fenêtre de conversion d'adrénaline gagne [D_SURGE] : [BLOCK]. <br>De plus, pendant l'étape « Convertir les adrénalines de défense », avant de convertir les résultats [D_SURGE], l'attaquant subit une blessure si le joueur a obtenu au moins un résultat [D_SURGE] dans son jet de défense. <br><br>Quand une unité ayant CE mot-clé utilise le mot-clé Gardien X, avant de convertir des adrénalines de défense avec le mot-clé Maîtrise du Soresu, l'attaquant subit une blessure si au moins un des dés lancés par le mot-clé Gardien X a produit au moins un résultat [D_SURGE]. <br><br>Si le mot-clé Déflexion permet de vaincre l'unité attaquante, l'attaque continue et le défenseur peut toujours subir des blessures. <br>Tant qu'une unité défend ou utilise le mot-clé Gardien X contre une attaque dont la réserve d'attaque contient uniquement des armes dotées du mot-clé Haute Vélocité, le mot-clé Déflexion n'a pas d'effet.", 

"DEMORALIZE X - DEMORALISER X": "Après qu'une unité dotée de CE mot-clé a effectué son étape « Se rallier », ajoutez jusqu'à X [SUPPRESSION] à des unités ennemies à [RANGE 2].", 

"DETACHMENT : UNIT NAME/TYPE - DETACHEMENT : NOM/TYPE D'UNITE": "Pendant la création d'armée, une unité dotée de CE mot-clé ne compte pas dans le nombre maximal d'unités de son rang pouvant être incluses. <br>Une unité dotée de CE mot-clé ne peut être incluse dans l'armée d'un joueur que si une autre unité qui porte le nom ou est du type spécifié, et qui n'est pas dotée de CE mot-clé, est également incluse dans cette armée. <br>Chaque unité dotée de CE mot-clé doit être associée à sa propre unité spécifiée. <br><br>De plus, pendant l'étape « Se déployer sur les positions préparées », une unité dotée de CE mot-clé gagne le mot-clé Infiltration ou Position Préparée jusqu'à la fin de la partie si l'unité spécifiée correspondante est dotée de ce mot-clé. <br><i>Par exemple, une joueuse souhaite ajouter un Soldat avec Mortier DF-90 à son armée. Comme le Soldat avec Mortier DF-90 est doté du mot-clé Détachement : Shoretroopers, la joueuse doit ajouter une unité de Shoretroopers à son armée avant d'ajouter le Soldat avec Mortier DF-90. La joueuse s'exécute, son armée contient donc désormais une unité de Shoretroopers et une unité de Soldat avec Mortier DF-90. La joueuse souhaite ensuite ajouter une seconde unité de Soldat avec Mortier DF-90 à son armée : elle doit donc d'abord sélectionner une seconde unité de Shoretroopers à inclure dans son armée.</i>", 

"DISCIPLINED X - DISCIPLINE X": "Après qu'une unité dotée de CE mot-clé a reçu un ordre, elle peut retirer jusqu'à X [SUPPRESSION].", 

"INCONSPICUOUS - DISCRET": "Tant qu'une unité dotée de CE mot-clé possède au moins un [SUPPRESSION], lorsqu'une unité ennemie effectue une attaque, elle doit cibler une autre unité, si possible. <br>Lorsqu'une unité dotée de CE mot-clé se rallie, elle peut choisir de ne pas retirer un nombre de [SUPPRESSION] de son choix, y compris zéro.", 

"DISTRACT - DISTRAIRE": "En tant qu'action de carte gratuite, une unité dotée de CE mot-clé peut choisir une unité de soldats ennemie à [RANGE 2] et en LdV. Jusqu'à la fin du round, lorsque l'unité ennemie choisie effectue une attaque, elle doit attaquer l'unité qui a utilisé Distraire, si possible. <br>Tant que l'unité ennemie choisie attaque l'unité dotée de CE mot-clé, chaque figurine de l'unité ennemie doit choisir une arme éligible afin de l'ajouter à une réserve d'attaque. <br>L'unité ennemie peut déclarer des défenseurs supplémentaires et constituer des réserves de dés supplémentaires uniquement si, après avoir constitué une réserve de dés avec des armes éligibles, il reste des armes que des figurines de l'unité peuvent utiliser et qui n'étaient pas éligibles pour contribuer à la première réserve d'attaque. <br>Lorsqu'une unité utilise CE mot-clé, si elle était dotée du mot-clé Discret, elle le perd jusqu'à la fin du round.",

"DUELIST - DUELLISTE": "Lorsqu'une unité dotée de CE mot-clé effectue une attaque au corps-à-corps, si elle dépense un ou plusieurs [AIM] pendant l'étape « Relancer les dés d'attaque », la réserve d'attaque gagne le mot-clé d'arme Perforant 1. <br><br>Tant qu'une unité dotée de CE mot-clé défend contre une attaque au corps-à-corps, si elle dépense au moins un [DODGE] pendant l'étape « Appliquer les esquives et couverts », elle gagne le mot-clé Immunité : perforant. <br><br>L'unité dotée de CE mot-clé bénéficie de ces effets en plus des effets normaux déclenchés en utilisant des [AIM] et [DODGE].",

"SCOUT X - ECLAIREUR X": "Lorsqu'une unité non déployée dotée de CE mot-clé s'active, au début de l'étape « Effectuer des actions », elle peut se déployer en effectuant une action Se déplacer à vitesse X gratuite, en ignorant le terrain difficile. <br>Une unité peut effectuer ce déplacement quelle que soit sa vitesse maximale. <br>CE mot-clé peut se cumuler, mais pas au-dessus de 3. Si une unité est censée être dotée d'Éclaireur X au-dessus de 3, elle est dotée d'Éclaireur 3 à la place.", 

"ENRAGE X": "Lorsqu'une unité dotée de CE mot-clé possède un nombre de pions Blessure supérieur ou égal à X, cette unité gagne le mot-clé Charge. <br>De plus, elle considère sa valeur de courage comme « - » et perd tout [SUPPRESSION] qu'elle possède. <br><br>Si une unité dotée du mot-clé Enragé X possède un nombre de pions Blessure supérieur ou égal à X, mais qu'elle retire des pions Blessure grâce à un effet et se retrouve avec moins de pions Blessure que X, elle ne bénéficie plus de CE mot-clé jusqu'à ce qu'elle ait de nouveau un nombre de pions Blessure supérieur ou égal à X.", 

"ENTOURAGE : UNIT NAME - ENTOURAGE : NOM D'UNITÉ": "Pendant la création d'armée, si un joueur inclut une unité dotée de CE mot-clé, une unité spécifiée par le mot-clé Entourage ne compte pas dans le nombre maximal d'unités de son rang pouvant être incluses. <br>Un joueur peut donc inclure plus d'unités d'un rang spécifique qu'autorisé par les prérequis de rang. <br>Lors de la Phase de Commandement, pendant l'étape « Nommer des Commandants et donner des ordres », une unité dotée de CE mot-clé peut donner un ordre à une unité alliée à [RANGE 2] portant le nom spécifié par CE mot-clé. <br><br>De plus, l'unité spécifiée par CE mot-clé ignore le prérequis de rang [TROUPIER] pour prêter main-forte à l'unité dotée du mot-clé Entourage. <br><i>Par exemple, le Directeur Orson Krennic est doté du mot-clé Entourage : Death Troopers. Si une armée inclut le Directeur Orson Krennic, 1 unité de Death Troopers de la même armée ne compte pas dans le nombre maximal d'unités du rang forces spéciales autorisé dans l'armée, ce qui permet au joueur d'inclure jusqu'à trois autres unités de forces spéciales en plus des Death Troopers. Lors de la Phase de Commandement, le Directeur Orson Krennic peut donner un ordre à une unité de Death Troopers à 2.</i>", 

"EQUIP - EQUIPE": "Pendant la création d'armée, si un joueur inclut une unité dotée de CE mot-clé, cette unité doit s'équiper des améliorations spécifiées après le mot-clé.",

"HEAVY WEAPON TEAM - EQUIPE AVEC ARME LOURDE": "Une unité dotée de CE mot-clé doit s'équiper d'une carte [ARME_LOURDE]. La figurine ajoutée à l'unité grâce à cette carte Amélioration devient le Chef d'unité.", 

"SCOUTING PARTY X - EQUIPE D'ECLAIREURS X": "Pendant la mise en place, le joueur contrôlant une unité dotée de CE mot-clé peut choisir jusqu'à X unités de soldats alliées appartenant à la même faction ou affiliation que cette unité et qui ne sont pas dotées du mot-clé Éclaireur. Chaque unité choisie gagne le mot-clé Éclaireur X jusqu'à la fin de la partie, X étant égal à la valeur d'Éclaireur X de l'unité dotée du mot-clé Équipe d'Éclaireurs X.", 

"RETINUE : UNIT/UNIT TYPE - ESCORTE : NOM/TYPE D'UNITE": "Au début de la Phase d'Activation, si une unité dotée de CE mot-clé se trouve à [RANGE 2] d'une autre unité ou type d'unité allié(e) spécifié(e) par CE mot-clé, elle gagne soit un [AIM], soit un [DODGE]. <br><br>De plus, une unité dotée de CE mot-clé ignore le prérequis de rang [TROUPIER] pour prêter main-forte à l'unité spécifiée. ", 

"EXEMPLAR - EXEMPLAIRE": "Tant qu'elle attaque ou défend, si une unité alliée se trouve à [RANGE 2] et en LdV d'une ou plusieurs unités alliées dotées de CE mot-clé et qui appartiennent à la même faction ou affiliation que l'unité attaquante ou en défense, cette unité attaquante ou en défense peut dépenser un [AIM], [DODGE] ou [SURGE] appartenant à une de ces unités dotées de CE mot-clé comme si cette unité attaquante ou en défense possédait le pion.", 

"RELIABLE X - FIABLE X": "Au début de la Phase d'Activation, une unité dotée de CE mot-clé gagne X [SURGE].", 

"SMOKE X - FUMEE X": "Une unité dotée de CE mot-clé peut effectuer l'action Fumée X. Pour effectuer cette action, l'unité place X pions Fumée intégralement à [RANGE 1] et en LdV de son Chef d'unité. <br>Les pions Fumée ne peuvent pas chevaucher les pions Objectif, Avantage et Charge, ni les autres pions Fumée, et ils doivent être placés sur une surface plane. <br>PIONS FUMÉE : les unités de soldats dont le Chef se trouve à [RANGE 1] d'un pion Fumée améliorent de 1 la valeur numérique de leur couvert au cours de l'étape « Déterminer le couvert ». <br>Tant qu'une unité de soldats attaque, si le Chef de l'unité attaquante se trouve à [RANGE 1] d'un pion Fumée, l'unité en défense améliore de 1 la valeur numérique de son couvert. Les effets qui améliorent le couvert d'une unité peuvent se cumuler. Une unité ne peut pas être affectée par un même pion Fumée plus d'une fois. Les pions Fumée sont retirés pendant l'étape « Retirer les pions » de la Phase Finale. <br><i>Par exemple, une unité de soldats dont le Chef d'unité se trouve à [RANGE 1] de 2 pions Fumée améliore de 2 la valeur numérique de son couvert.</i>", 

"GUARDIAN X - GARDIEN X": "Tant qu'une unité de soldats alliée à [RANGE 1] et en LDV d'une unité dotée de CE mot-clé défend contre une attaque à distance, elle peut annuler jusqu'à X résultats [HIT] au cours de l'étape « Modifier les dés d'attaque » de la séquence d'attaque. <br>Pour chaque [HIT] annulé de cette manière, l'unité dotée de CE mot-clé lance un dé de défense correspondant à celui de sa carte Unité. Après avoir converti [D_SURGE] en fonction de sa fenêtre d'adrénaline ou grâce à des [SURGE], l'unité dotée de CE mot-clé gagne 1 [SUPPRESSION], puis subit 1 blessure pour chaque résultat vierge. <br>Une unité en défense sur laquelle CE mot-clé est utilisé gagne un [SUPPRESSION] normalement. <br>Une unité ne peut pas utiliser Gardien X si l'unité en défense est également dotée du mot-clé Gardien X. <br>Si plusieurs unités alliées peuvent utiliser CE mot-clé au cours d'une attaque, le joueur qui contrôle ces unités déclare quelle unité utilise CE mot-clé et résout sa capacité avant de choisir s'il déclare qu'une autre unité utilise CE mot-clé. <br>Une unité ne peut pas utiliser Gardien X si elle possède un nombre de [SUPPRESSION] supérieur ou égal à sa valeur de courage. <br><br>Le mot-clé Perforant X peut être utilisé pour annuler des résultats [BLOCK] sur des dés de défense lancés par une unité utilisant Gardien X ; considérez les résultats [BLOCK] annulés comme des résultats vierges. <br>Après une telle utilisation du mot-clé Perforant X, toute valeur de Perforant X non utilisée peut toujours être utilisée pour annuler des résultats [BLOCK] obtenus par l'unité en défense. <br><br>De plus, une unité dotée de CE mot-clé ne peut pas se faire prêter main-forte et ignore le prérequis de rang [TROUPIER] pour prêter main-forte.", 

"GENERATOR X - GENERATEUR X": "Pendant la Phase Finale, une unité dotée de CE mot-clé peut retourner jusqu'à X pions Bouclier inactifs afin d'afficher leur côté actif.",

"EXPERT CLIMBER - GRIMPEUR EXPERIMENTE": "Lorsqu'une unité dotée de CE mot-clé grimpe, elle peut parcourir une distance verticale allant jusqu'à 2 de hauteur.", 

"AI : ACTION - IA : ACTION": "Quand une unité dotée de CE mot-clé commence son étape « Effectuer des actions », si elle n’a pas de pion Ordre face visible et si 1 des conditions listées ci-dessous est remplie, elle doit effectuer 1 des actions spécifiées par son mot-clé IA.<br>• L’unité est démoralisée mais pas paniquée. <br>• L’unité possède un pion Dégât de véhicule. <br>• C’est une unité de véhicule et au moins la moitié de ses figurines avec lesquelles elle a commencé la partie ont été vaincues. <br>Si l’unité ne peut effectuer aucune des actions spécifiées par son mot-clé IA, elle effectue une action de moins lors de son étape « Effectuer des actions »", 

"IMMUNE : RANGE 1 WEAPONS - IMMUNITE : ARMES PORTEE 1": "Une réserve d'attaque attribuée à une unité dotée de CE mot-clé ne peut pas contenir d'armes ayant une portée maximale de 1.",

"IMMUNE : MELEE - IMMUNITE : CORPS-A-CORPS": "Les unités dotées de CE mot-clé ne peuvent pas être ciblées par des attaques au corps-à-corps et ne peuvent pas être engagées. <br>Lorsqu’elle constitue une réserve d’attaque qui cible une unité ayant Immunité : corps-à-corps, l’unité attaquante peut ajouter des armes à distance à la réserve d’attaque, même si elle est au corps-à-corps avec l’unité en défense.",

"IMMUNE : BLAST - IMMUNITE : DEFLAGRATION": "Tant qu'une unité dotée de CE mot-clé défend, les effets du mot-clé Déflagration sont ignorés.", 

"IMMUNE : ENEMY EFFECTS - IMMUNITE : EFFETS ENNEMIS": "Une unité dotée de CE mot-clé ignore tous les effets des cartes ennemies et ne peut pas être ciblée par les effets des cartes ennemies.", 

"IMMUNE : PIERCE - IMMUNITE : PERFORANT": "Tant qu'une unité dotée de CE mot-clé défend, l'attaquant ne peut pas utiliser le mot-clé d'arme Perforant X pour annuler des résultats [BLOCK] des dés de défense pendant l'étape « Modifier les dés de défense ». <br><br>Tant qu'une unité dotée de CE mot-clé utilise le mot-clé Gardien X, l'unité attaquante ne peut pas utiliser le mot-clé Perforant X pour annuler des résultats [BLOCK] obtenus sur les dés de défense lancés par cette unité pour le mot-clé Gardien X.", 

"IMMUNE : MELEE PIERCE - IMMUNITE : PERFORANT AU CORPS-A-CORPS": "Tant qu'une unité dotée de CE mot-clé défend contre une attaque au corps-à-corps, l'attaquant ne peut pas utiliser le mot-clé d'arme Perforant X pour annuler des résultats [BLOCK] des dés de défense pendant l'étape « Modifier les dés de défense ». <br><br>Tant qu'une unité dotée de CE mot-clé utilise le mot-clé Gardien X au cours d'une attaque au corps-à-corps, l'unité attaquante ne peut pas utiliser le mot-clé Perforant X pour annuler des résultats [BLOCK] obtenus sur les dés de défense lancés par cette unité pour le mot-clé Gardien X.", 

"RUTHLESS - IMPITOYABLE": "Lorsqu'une autre unité de soldats [TROUPIER] alliée à [RANGE 2] et en LdV qui possède un pion Ordre face visible s'active, elle peut subir 1 blessure pour effectuer 1 action gratuite.", 

"RELENTLESS - IMPLACABLE": "Après qu'une unité dotée de CE mot-clé a effectué au cours de son activation une action Se Déplacer, elle peut effectuer une action Attaquer gratuite.", 

"UNSTOPPABLE - INARRETABLE": "Une unité dotée de CE mot-clé est éligible pour s'activer pendant la Phase d'Activation tant qu'elle possède au maximum 1 pion Ordre. Cette unité ne peut jamais posséder plus d'un pion Ordre face visible. <br>Tant que cette unité n'est pas vaincue, lors de la constitution de sa réserve d'ordres, le joueur qui la contrôle ajoute à sa réserve d'ordres un pion Ordre supplémentaire correspondant au rang de cette unité.", 

"INCOGNITO": "Une unité dotée de CE mot-clé ne peut pas être attaquée par des unités ennemies se trouvant au-delà de [RANGE 1] de cette dernière. <br>De plus, elle ne peut pas contester d'objectifs, ni prêter main-forte. <br>Si une unité dotée de CE mot-clé effectue une attaque ou défend contre une attaque, elle perd toutes les règles spéciales de CE mot-clé jusqu'à la fin de la partie. <br><br>De plus, au début de l'activation d'une unité dotée de CE mot-clé, elle peut choisir de perdre les règles spéciales du mot-clé Incognito jusqu'à la fin de la partie.", 

"UNCONCERNED - INDIFFERENT": "Une unité dotée de CE mot-clé ne peut pas bénéficier d'un couvert, et les figurines de cette unité ne peuvent être ni réparées ni restaurées.", 

"INDOMITABLE - INDOMPTABLE": "Lorsqu'une unité dotée de CE mot-clé effectue son étape « Se rallier », elle lance des dés de défense rouges à la place de dés de défense blancs.", 

"INFILTRATE - INFILTRATION": "Au début de l'activation d'une unité non déployée dotée de CE mot-clé, elle peut se déployer en plaçant son Chef d'unité intégralement en territoire allié. <br>Ensuite, les autres figurines de cette unité sont placées en cohésion avec leur Chef d'unité et intégralement en territoire allié. <br>Les figurines ne peuvent pas chevaucher le terrain infranchissable lorsqu'elles sont placées en utilisant CE mot-clé.", 

"MECHANIZED INFANTRY - INFANTERIE MÉCANISÉE": "Au début de la Phase d’Activation, chaque unité dotée de CE mot-clé peut choisir une unité de véhicule alliée différente à [RANGE 2]. <br>Dans ce cas, l’unité dotée de CE mot-clé et chaque unité choisie gagnent 1 [AIM] ou 1 [DODGE].",
    
"DIVINE INFLUENCE - INFLUENCE DIVINE": "Tant qu'elles sont à [RANGE 1] et en LDV d'un C-3PO allié, les autres unités de soldats EWOKS alliées gagnent le mot-clé Gardien 2 : C-3PO. <br>Tant qu'elles utilisent Gardien, elles peuvent annuler les résultats [CRIT] comme s'il s'agissait de résultats [HIT].",

"IMPERVIOUS - INSENSIBLE": "Quand une unité dotée de CE mot-clé devrait avoir 1 ou plusieurs résultats [BLOCK] annulés par le mot-clé Perforant X, annulez en un de moins.",

"INSPIRE X - INSPIRATION X": "À la fin de l'activation d'une unité dotée de CE mot-clé, retirez au total jusqu'à X [SUPPRESSION] d'autres unités alliées à [RANGE 2].", 

"SELF-PRESERVATION - INSTINCT DE SURVIE": "Lorsque vous vérifiez si une unité dotée de CE mot-clé panique, cette unité ne peut pas utiliser la valeur de courage des unités n'appartenant pas à la même affiliation.",

"INTERROGATE - INTERROGATOIRE": "Pendant la Phase de Commandement, si un joueur révèle une carte Commandement qui appartient à une unité se trouvant à [RANGE 1] d'une ou plusieurs unités ennemies dotées de CE mot-clé et que les joueurs sont à égalité pour la priorité, considérez cette carte Commandement comme affichant un point lumineux supplémentaire.", 

"DAUNTLESS - INTREPIDE": "Après qu'une unité de soldats non-droïdes dotée de CE mot-clé a effectué son étape « Se rallier », si elle est démoralisée mais pas paniquée, au début de son étape « Effectuer des actions », elle peut gagner un [SUPPRESSION] afin d'effectuer une action Se déplacer gratuite. <br><br>Une unité dotée de CE mot-clé ne peut pas être affectée par le mot-clé Contrainte.",

"DANGER SENSE X - INTUITION DU DANGER X": "Lorsqu'une unité dotée de CE mot-clé est censée retirer n'importe quel nombre de ses [SUPPRESSION], elle peut choisir de ne pas retirer jusqu'à X pions, y compris zéro. <br>Tant qu'une unité dotée de CE mot-clé défend contre une attaque, elle lance un dé de défense supplémentaire pendant l'étape « Lancer les dés de défense » pour chaque [SUPPRESSION] qu'elle possède, jusqu'à X dés supplémentaires.", 

"I'M PART OF THE SQUAD TOO - JE FAIS AUSSI PARTIE DE L'EQUIPE": "Une unité dotée de CE mot-clé conteste un pion Objectif si son Chef d'unité se trouve à [RANGE 1] de ce pion, au lieu de [HALF-RANGE].",

"MY MOOD IS BASED ON PROFIT - JE SENS LE PROFIT": "Lorsque la valeur X est présente dans les mots-clés ou statistiques d'une unité dotée de CE mot-clé (SUR SA CARTE d'UNITE), X est égal au nombre de points lumineux figurant sur la carte Commandement que le joueur contrôlant cette unité a jouée et révélée le plus récemment lors de cette partie, jusqu'à un minimum de 1. <br>Si le joueur n'a pas encore joué et révélé de carte Commandement, considérez X comme 1.",

"DEATH FROM ABOVE - LA MORT VENUE DU CIEL": "Lorsqu'une unité dotée de CE mot-clé attaque, l'unité en défense ne peut pas utiliser un couvert pour annuler les résultats [HIT] au cours de l'étape « Appliquer le couvert » si le Chef de l'unité attaquante chevauche un élément de terrain non en zone d'une hauteur supérieure à tout terrain que le Chef de l'unité en défense chevauche.", 

"VICTORY OR DEATH - LA VICTOIRE OU LA MORT": "Lorsqu’une unité alliée dotée de CE mot-clé subit au moins 1 blessure d’une attaque ennemie, après la résolution de l’attaque, cette unité alliée peut gagner 1 [SUPPRESSION]. <br>Dans ce cas, elle peut gagner 1 [AIM] ou 1 [DODGE].",   

"MANDALORIANS ARE STRONGER TOGETHER - LES MANDALORIENS SONT PLUS FORTS ENSEMBLE": "Lorsqu’une unité alliée dotée de CE mot-clé dépense au moins 1 [AIM], après que l’effet a été résolu, elle gagne 1 [DODGE] si elle est à [RANGE 2] d’une autre unité alliée dotée de CE mot-clé.<br>Lorsqu’une unité alliée dotée de CE mot-clé dépense au moins 1 [DODGE], après que l’effet a été résolu, elle gagne 1 [AIM] si elle est à [RANGE 2] d’une autre unité alliée dotée de CE mot-clé.",
   
"ONE STEP AHEAD - LONGUEUR D'AVANCE": "Si une ou plusieurs unités alliées sont dotées de CE mot-clé, pendant l'étape Résoudre les cartes Commandement, après avoir révélé les cartes Commandement mais avant d'en résoudre les effets, si le nombre de points lumineux présents sur les cartes Commandement révélées ne correspond pas, 1 unité alliée dotée de CE mot-clé et se trouvant sur le champ de bataille peut effectuer un déplacement à vitesse 1. <br>Si le nombre de points lumineux correspond, et qu'il y a 1 ou plusieurs unités alliées dotées CE mot-clé sur le champ de bataille, choisissez une unité alliée se trouvant sur le champ de bataille. L'unité choisie peut effectuer un déplacement à vitesse 1.", 

"MASTER STORYTELLER - MAITRE CONTEUR": "Lorsqu'une unité effectue l'action de carte Maître Conteur, elle choisit jusqu'à X unités EWOKS alliées à [RANGE 2], X étant égal au numéro du round en cours. <br>Chaque unité choisie gagne 2 [SURGE].",

"MASTER OF THE FORCE X - MAITRE DE LA FORCE": "À la fin de son activation, une unité dotée de CE mot-clé peut redresser jusqu'à X de ses cartes [FORCE] inclinées.", 
 
"ATARU MASTERY - MAITRISE DE L'ATARU": "Une unité dotée de CE mot-clé peut effectuer jusqu'à deux actions Attaquer au cours de son activation. <br>Lorsqu'elle attaque, elle gagne un [DODGE] une fois que l'attaque est résolue. <br>Lorsqu'elle défend, elle gagne un [AIM] une fois l'attaque résolue.", 

"DJEM SO MASTERY - MAITRISE DU DJEM SO": "Lorsqu'une unité dotée de CE mot-clé défend contre une attaque au corps-à-corps, pendant l'étape « Comparer les résultats », l'unité attaquante subit une blessure si le jet d'attaque contient un ou plusieurs résultats vierges.",

"JAR'KRAY MASTERY - MAITRISE DU JAR'KAI": "Tant qu'elle effectue une attaque au corps-à-corps, une unité dotée de CE mot-clé peut, après avoir converti les adrénalines d'attaque au cours de l'étape « Convertir les adrénalines d'attaque », dépenser n'importe quel nombre de [DODGE]. <br>Pour chaque [DODGE] ainsi dépensé, transformez un résultat vierge en un résultat [HIT] ou un résultat [HIT] en un résultat [CRIT], ou bien dépensez deux [DODGE] pour transformer un résultat vierge en résultat [CRIT].", 

"JUYO MASTERY - MAITRISE DU JUYO": "Tant qu'une unité dotée de CE mot-clé possède un ou plusieurs pions Blessure, elle peut effectuer une action supplémentaire pendant son activation. <br>Une unité dotée de CE mot-clé ne peut effectuer que deux actions Se déplacer pendant son activation, actions gratuites incluses.", 

"MAKASHI MASTERY - MAITRISE DU MAKASHI": "Tant qu'une unité dotée de CE mot-clé effectue une attaque au corps-à-corps, pendant l'étape « Choisir les armes et rassembler les dés », elle peut réduire de 1 la valeur de Perforant X d'une arme de la réserve d'attaque. <br>Dans ce cas, le défenseur ne peut pas utiliser les mots-clés Immunité : perforant au corps-à-corps, Immunité : perforant et Insensible au cours de cette attaque.", 
 
"SHIEN MASTERY - MAITRISE DU SHIEN": "Lorsqu'une unité dotée de CE mot-clé utilise le mot-clé Déflexion, l'attaquant subit 1 blessure pour chaque résultat [D_SURGE] du jet de défense à la place de toute autre blessure que le mot-clé Déflexion aurait dû provoquer. <br>De plus, quand une unité dotée de CE mot-clé est l'unité en défense d'une attaque à distance, si elle ne subit pas de blessures lors de cette attaque, elle ne gagne pas de [SUPPRESSION] pendant l'étape « Attribuer un [SUPPRESSION] au défenseur » de cette attaque.", 

"SORESU MASTERY - MAITRISE DU SORESU": "Lorsqu'une unité dotée de CE mot-clé défend contre une attaque à distance, elle peut relancer tous ses dés de défense au cours de l'étape « Relancer les dés de défense ». <br>De plus, lorsqu'une unité dotée de CE mot-clé utilise le mot-clé Gardien X, elle peut dépenser un [DODGE] avant de convertir les résultats [D_SURGE]. Dans ce cas, elle relance tous ses dés de défense avant de convertir les résultats [D_SURGE]. <br>Chaque dé ne peut pas être relancé plus d'une fois grâce à Maîtrise du Soresu.",

"VAAPAD MASTERY - MAÎTRISE DU VAAPAD": "Lorsqu’une unité dotée de CE mot-clé attaque, avant de lancer les dés, elle ajoute 1 dé d’attaque blanc à la réserve pour chaque pion Blessure qu’elle possède, pour un maximum de 3. <br>Lorsqu’une unité dotée du mot-clé Maîtrise du Vaapad défend, avant de lancer les dés, elle ajoute 1 dé de défense blanc à la réserve pour chaque pion Blessure qu’elle possède, pour un maximum de 3.",
    
"CUNNING - MALIN": "Pendant la Phase de Commandement, si un joueur révèle une carte Commandement spécifique aux [COMMANDANT] ou aux [AGENT] qui appartient à une unité dotée de CE mot-clé et que les joueurs sont à égalité pour la priorité, considérez cette carte Commandement comme affichant un point lumineux de moins pour un minimum de 0. <br><br>Si les deux joueurs révèlent une carte Commandement spécifique aux [COMMANDANT] ou aux [AGENT] qui appartient à une unité dotée de CE mot-clé, l'égalité pour la priorité demeure.", 

"OUTMANEUVER - MANŒUVRE IMPROBABLE": "Pendant l'étape « Appliquer les esquives et couverts », une unité dotée de CE mot-clé peut dépenser des [DODGE] pour annuler des résultats [CRIT].", 

"SPUR - MARCHE FORCEE": "Lorsqu'une unité dotée de CE mot-clé se déplace, son contrôleur peut lui attribuer un [SUPPRESSION] afin d'augmenter de 1 sa vitesse maximale pour ce déplacement, jusqu'à un maximum de 3. <br>Lorsqu'une unité se déplace, appliquez tout effet qui augmente sa vitesse maximale avant d'appliquer les effets qui réduisent la vitesse maximale de cette unité. <br><i>Par exemple, une unité ayant normalement une vitesse maximale de 1, mais qui possède 1 pion Immobilisation, peut utiliser le mot-clé Marche Forcée pour effectuer un déplacement d'une vitesse maximale totale de 1. Néanmoins, une unité ayant normalement une vitesse maximale de 1, mais qui possède 2 pions Immobilisation, ne peut pas utiliser le mot-clé Marche Forcée pour effectuer un déplacement car sa vitesse maximale sera alors égale à 0.</i>", 

"SWASHBUCKLER - MATAMORE": "Lorsqu’une unité dotée de CE mot-clé dépense au moins 1 [AIM] lors d’une action Attaquer, après que l’effet a été résolu, elle gagne 1 [DODGE].",
    
"MERCENERY : FACTION - MERCENAIRE : FACTION": "Une unité dotée de CE mot-clé est une unité de mercenaire. La ou les factions spécifiées par CE mot-clé peuvent inclure cette unité dans une armée en tant qu'unité de mercenaire.", 

"TAKE COVER X - METTRE A COUVERT X": "En tant qu'action de carte, une unité dotée de CE mot-clé peut choisir jusqu'à X unités alliées à [RANGE 2]. Chaque unité choisie gagne un [DODGE].", 

"SECRET MISSION - MISSION SECRETE": "Au début de chaque Phase de Commandement, si une unité dotée de CE mot-clé se trouve intégralement en territoire ennemi, elle gagne un pion Mission secrète. <br>Une unité ne peut gagner qu'un seul pion Mission secrète lors de la partie. <br>Au moment de marquer des PV, si un joueur contrôle une ou plusieurs unités ayant un pion Mission secrète et que ces unités se trouvent intégralement en territoire ennemi, ce joueur peut décider de retirer ces pions Mission secrète. <br>Il marque 1 PV pour chaque pion Mission secrète ainsi retiré.", 

"MOBILE": "Lorsqu'une unité ayant un socle avec encoches dotée de CE mot-clé effectue un déplacement, elle saute l'étape 1 de la section « Déplacement des socles avec encoches », consistant à tourner le socle du Chef d'unité.<br>Une unité dotée de CE mot-clé doit effectuer une action Se déplacer obligatoire gratuite au début ou à la fin de son étape « Effectuer des actions ». <br> Une unité dotée de CE mot-clé ne peut pas reculer.<br>Si une unité dotée de CE mot-clé effectue plusieurs actions Se déplacer non obligatoires au cours de son activation, elle ne peut pas revendiquer de pions Atout pendant cette activation. <br><br>De plus, une unité dotée du mot-clé Mobile qui a revendiqué un pion Atout ne peut effectuer qu’une seule action Se déplacer non obligatoire pendant son activation.",

"PLODDING - MOBILITE DIFFICILE": "Pendant son activation, une unité dotée de CE mot-clé ne peut effectuer qu'une action Se déplacer.", 

"WHEEL MODE - MODE ROUE": "Au début de son activation, une unité dotée de CE mot-clé peut changer sa vitesse pour être à vitesse 3 jusqu’à la fin de cette activation. <br>Dans ce cas, jusqu’à la fin du round, elle perd le mot-clé Indifférent, gagne les mots-clés IA : Déplacement et Couvert 2, et ne peut pas retourner ses pions Bouclier actifs.<br>Pour indiquer qu'une unité de Droïdekas utilise le Mode Roue, un joueur peut remplacer ses figurines de Droïdekas debout par des figurines de Droïdekas en roue, ou placer à côté de l'unité un pion Mode Roue. Les joueurs ne doivent utiliser les figurines de Droïdekas en roue que lorsque l'unité utilise le mot-clé Mode Roue et uniquement jusqu'à la fin du round : les figurines de Droïdekas en roue doivent alors toutes être remplacées par des figurines debout.", 

"WE FIGHT FOR OUR FAMILY - NOUS NOUS BATTONS POUR NOTRE FAMILLE": "Lorsqu’une unité alliée dotée de CE mot-clé effectue une action Attaquer, après que l’effet a été résolu, choisissez une autre unité alliée dotée de CE mot-clé à [RANGE 2],si possible. L’unité choisie gagne 1 [DODGE].",
    
"SPOTTER X - OBSERVATEUR X": "En tant qu'action de carte, une unité dotée de CE mot-clé peut choisir jusqu'à X unités alliées se trouvant à [RANGE 2]. Chaque unité choisie gagne un [AIM].", 
 
"WE'RE NOT REGS - ON EST PAS DES REGS": "Une unité dotée de CE mot-clé ne peut pas dépenser de PIONS VERTS sur d'autres unités de soldats clones, et les autres unités de soldats clones ne peuvent pas dépenser les PIONS VERTS de cette unité. <br><br>De plus, cette unité ne peut pas se faire prêter main-forte.",

"READY X - OPERATIONNEL X": "Après qu'une unité dotée de CE mot-clé a effectué une action Attendre, elle gagne X [AIM].", 
 
"DIRECT : UNIT NAME/UNIT TYPE - ORDRE DIRECT : NOM/TYPE D'UNITE": "Lors de chaque Phase de Commandement, pendant l'étape « Nommer des Commandants et donner des ordres », une unité dotée de CE mot-clé peut donner un ordre à une unité alliée à [RANGE 2] portant le nom ou étant du type spécifié.", 

"COMMAND VEHICLE X - PILOTAGE DE VÉHICULE X": "Quand une unité alliée à [RANG 3] d’une unité dotée de CE mot-clé vérifie si elle est paniquée, si les deux unités ont la même affiliation ou faction, l’unité alliée considère que l’unité dotée de CE mot-clé est une unité [COMMANDANT] ayant une valeur de COURAGE de X",
    
"GUNSLINGER - PISTOLERO": "Lorsqu'une unité dotée de CE mot-clé effectue son étape « Déclarer un défenseur supplémentaire », elle peut déclarer un défenseur supplémentaire et créer une réserve d'attaque consistant uniquement en une arme à distance qui a déjà été ajoutée à une autre réserve d'attaque. Le mot-clé Pistolero ne peut être utilisé qu'une fois par séquence d'attaque.", 

"FULL PIVOT - PIVOT COMPLET": "Lorsqu'une unité dotée de CE mot-clé pivote, elle peut pivoter jusqu'à 360°.", 

"WEAK POINT X : FRONT/REAR/SIDES - POINT FAIBLE X : AVANT/ARRIERE/FLANCS": "Tant qu'une unité dotée de CE mot-clé : avant/arrière/flancs défend, si le Chef de l'unité attaquante se trouve au moins partiellement dans l'arc de tir spécifié de l'unité en défense, la réserve d'attaque gagne le mot-clé Impact X, X étant alors égal à la valeur de Point Faible X. <br>Tant qu'une unité dotée de CE mot-clé défend contre une attaque à distance effectuée par une arme à effet de zone, considérez le pion Charge ou Avantage comme étant le Chef de l'unité attaquante.", 

"PREPARED POSITION - POSITION PREPAREE": "Pendant l'étape « Se déployer sur les positions préparées » de la mise en place, une unité dotée de CE mot-clé peut se déployer en plaçant son Chef d'unité intégralement en territoire allié. <br>Ensuite, les figurines restantes de l'unité sont placées en cohésion avec leur Chef d'unité et intégralement en territoire allié. Cette unité gagne ensuite 1 [DODGE]. <br>Les figurines ne peuvent pas chevaucher un terrain infranchissable lorsqu'elles sont placées en utilisant Position Préparée.", 

"LATENT POWER - POUVOIR LATENT": "À la fin de l'activation d'une unité dotée de CE mot-clé, elle peut gagner 1 [SUPPRESSION] afin de lancer 1 dé de défense rouge. <br>Dans ce cas, <br>Sur un résultat [D_SURGE], choisissez une unité ennemie à [RANGE 1] de cette figurine. L'unité choisie gagne 2 [SUPPRESSION] et 2 pions Immobilisation. <br>Sur un résultat vierge, retirez 1 pion Blessure ou Poison d'une unité de soldats non-droïde alliée à [RANGE 1] de cette figurine.",

"PRECISE X - PRECIS X": "Lorsqu'une unité attaquante dotée de CE mot-clé dépense un [AIM] pendant l'étape « Relancer les dés d'attaque », elle peut relancer jusqu'à X dés d'attaque supplémentaires par [AIM] dépensé.",

"AGILE X - PRESTE X": "CE mot-clé permet à une unité de gagner X [DODGE] à chaque fois qu'elle effectue un déplacement normal au cours d'une action ou d'une action gratuite.", 

"BOUNTY - PRIME": "Pendant la mise en place, une unité dotée de CE mot-clé choisit une unité [AGENT] ou [COMMANDANT] ennemie : cette dernière gagne un pion Butin. <br>Après qu'une unité alliée dotée de CE mot-clé a vaincu, grâce à un effet ou une attaque, une unité ennemie dotée d'un ou plusieurs pions Prime, le contrôleur de l'unité alliée marque 1 PV.", 

"LOW PROFILE - PROFIL BAS": "Tant qu'elle défend contre une attaque à distance, si une unité dotée de CE mot-clé doit lancer un ou plusieurs dés de défense pendant l'étape « Lancer la réserve de couvert », elle lance un dé de défense de moins et ajoute à la place un résultat [BLOCK] supplémentaire à la réserve de couvert après le jet.",
 
"PROGRAMMED - PROGRAMME": "Une unité dotée de CE mot-clé doit s'équiper d'au moins une carte [PROGRAMMATION] pendant la création d'armée.",

"RECHARGE X - RECHARGER X": "Lorsqu'une unité dotée de CE mot-clé récupère, elle peut retourner jusqu'à X pions Bouclier inactifs sur leur côté actif.", 

"REPOSITION - REDEPLOIEMENT": "Lorsqu'une unité dotée de CE mot-clé effectue un déplacement normal, elle peut effectuer un pivot avant ou après avoir effectué le déplacement normal.", 

"REGENERATE X - REGENERER X": "À la fin de l'activation d'une unité, si elle est dotée de CE mot-clé, elle lance un dé de défense blanc pour chaque pion Blessure qu'elle possède, pour un maximum de X pions. <br>Pour chaque résultat [BLOCK] ou [D_SURGE] obtenu, elle retire un pion Blessure.", 

"REINFORCEMENTS - RENFORTS": "Au début de la Phase Finale du round 1 d'une partie, une unité dotée de CE mot-clé peut effectuer un déplacement gratuit à vitesse 1.",

"DISENGAGE - RETRAIT": "Tant qu'une unité de soldats dotée de CE mot-clé est engagée avec une seule unité ennemie, elle peut effectuer des déplacements normalement.", 

"FLEXIBLE RESPONSE X - RIPOSTE GRADUEE X": "Pendant la création d'armée, une unité dotée de CE mot-clé doit s'équiper de X [ARME_LOURDE].", 

"UNHINDERED - SANS ENTRAVE": "Lorsqu'une unité dotée de CE mot-clé effectue un déplacement, elle ne réduit pas sa vitesse maximale pour entrer dans un terrain difficile, en sortir ou le traverser.", 

"JUMP X - SAUT X": "Une unité dotée de CE mot-clé peut effectuer l'action de carte Saut X à tout moment auquel elle peut effectuer une action Se déplacer. <br>L'unité effectue une action Se déplacer normalement et peut ignorer le terrain ou mettre fin à ce déplacement sur un terrain de hauteur X ou moins. <br>Tant qu'elle effectue un déplacement avec l'action accordée par Saut X, une unité ignore les effets des terrains difficiles et des autres figurines d'une hauteur inférieure ou égale à X. <br>Lorsqu'elle effectue un déplacement avec l'action Saut X, une unité peut placer le gabarit de déplacement à cheval sur un terrain infranchissable mais ne peut pas terminer son déplacement sur ce terrain infranchissable. <br>Lorsqu'une unité effectue l'action Saut X, mesurez la hauteur à partir de la position de départ de l'unité.", 

"SENTINEL - SENTINELLE": "Une unité dotée de CE mot-clé peut dépenser un pion [STANDBY] après qu'une unité ennemie a effectué une attaque, un déplacement ou une action à [RANGE 3] plutôt qu'à [RANGE 2].",

"SPECIAL ISSUE : BATTLE FORCE - SPECIFICITE : FORCE ARMEE": "Une unité dotée de CE mot-clé ne peut être incluse que dans une armée utilisant la force armée spécifiée.", 

"SPEEDER X": "Tant qu'elle se déplace, une unité dotée de CE mot-clé peut se déplacer ou terminer son déplacement sur un terrain d'une hauteur inférieure ou égale à X. <br><br>De plus, lorsqu'une unité ayant un socle avec encoches effectue un déplacement, elle saute l'étape 1 du déplacement des socles avec encoches, consistant à tourner le socle du Chef d'unité. <br>Une unité dotée de CE mot-clé doit effectuer une action Se déplacer obligatoire gratuite au début ou à la fin de son étape « Effectuer des actions ». <br>Si une unité dotée de CE mot-clé effectue plusieurs actions Se déplacer non obligatoires au cours de son activation, elle ne peut pas revendiquer de pions Atout au cours de cette activation. <br><br>De plus, une unité dotée de CE mot-clé qui a revendiqué un pion Atout ne peut effectuer qu'une seule action Se déplacer non obligatoire au cours de son activation. <br><br>DÉPLACEMENT OBLIGATOIRE : un déplacement obligatoire est une action Se déplacer gratuite. Pour effectuer un déplacement obligatoire, l'unité effectue un déplacement normal complet à sa vitesse maximale. Si elle ne peut pas, ou si un déplacement complet devait amener le socle de son Chef d'unité à se retrouver hors du champ de bataille, l'unité peut effectuer un déplacement partiel à la place, en terminant son déplacement le plus loin possible sur le gabarit de déplacement.", 

"STATIONARY - STATIONNAIRE": "Une unité dotée de CE mot-clé ne peut pas effectuer de déplacements, sauf des pivots.", 

"STRATEGIZE X - STRATEGE X": "Lorsqu'une unité utilise l'action Stratège X, elle gagne un [SUPPRESSION], puis elle choisit X unités alliées à [RANGE 2]. Chaque unité choisie gagne un [AIM] et un [DODGE].", 

"OVERRIDE - SURCHARGE": "Lorsqu’une unité alliée ayant le mot-clé IA débute son activation à [RANGE 3] d’au moins 1 unité alliée dotée de CE mot-clé, choisissez 1 de ces unités ayant Surcharge qui n’est pas paniquée.<br>L’unité choisie peut gagner 1 [SUPPRESSION]. <br>Dans ce cas, l’unité qui s’active ignore le mot-clé IA pendant son activation.", 

"OBSERVE X - SURVEILLANCE X": "En tant qu'action de carte ou action de carte gratuite, une unité dotée de CE mot-clé peut choisir une unité ennemie à [RANGE 3] et en LdV. <br>L'unité ennemie choisie gagne X [OBSERVATION]. Les [OBSERVATION] sont retirés pendant l'étape « Retirer les pions » de la Phase Finale. <br><br>Pendant une attaque, une unité attaquante alliée peut dépenser n'importe quel nombre de [OBSERVATION] qui appartiennent à l'unité en défense au cours de l'étape « Relancer les dés d'attaque ». <br>L'unité attaquante relance un dé d'attaque pour chaque [OBSERVATION] dépensé. <br>Les [OBSERVATION] sont dépensés un par un, et un même dé peut être relancé plusieurs fois en dépensant des [OBSERVATION] ou [AIM] en conséquence. <br>L'unité attaquante peut dépenser des [AIM] et [OBSERVATION] dans n'importe quel ordre.", 

"HOVER : GROUND/AIR X - SUSTENTATION : TERRESTRE/ AERIENNE X": "Une unité dotée de CE mot-clé peut effectuer des actions Attendre pendant l'étape « Effectuer des actions » et peut gagner et dépenser des [STANDBY]. <br>Une unité dotée de CE mot-clé peut reculer. <br><br>Une unité dotée du mot-clé Sustentation : terrestre X est considérée comme un véhicule terrestre par les autres unités pour vérifier la LdV. Pour tous les autres effets de jeu, l'unité reste considérée comme un véhicule à répulseurs. <br><br>Une unité dotée du mot-clé Sustentation : aérienne X ignore le terrain de hauteur X ou moins lorsqu'elle se déplace et peut terminer un déplacement en chevauchant un tel terrain.",

"STRAFE MOVE - DERAPER": "Si l'unité dotée du mot-clé Sustentation : terrestre/aérienne X a un socle avec encoches latérales, l'unité peut déraper grâce à une action Se déplacer. <br>Déraper est un déplacement normal pour une figurine ayant un socle avec encoches et s'effectue comme tel, à l'exception des points suivants : <br>• Pour effectuer un dérapage complet, au lieu de placer le gabarit de déplacement dans l'encoche avant du socle du Chef de l'unité, placez-le dans une des encoches latérales. Ensuite, déplacez la figurine et placez son encoche latérale opposée à l'autre extrémité du gabarit de déplacement. <br>• Pour effectuer un dérapage partiel, au lieu de placer le gabarit de déplacement dans l'encoche avant du socle du Chef de l'unité au début du déplacement, placez-le dans une des encoches latérales. À la fin d'un dérapage partiel, la figurine doit être placée de telle sorte que la ligne reliant les deux encoches latérales (sur son socle) soit parallèle à la section du gabarit de déplacement que la figurine a atteinte à la fin de son déplacement. <br>• Lorsqu'elle dérape, une unité réduit de 1 sa vitesse, jusqu'à un minimum de 1.", 

"TACTICAL X - TACTICIEN X": "CE mot-clé permet à une unité de gagner un nombre de [AIM] égal à X chaque fois qu'elle effectue un déplacement normal lors d'une action ou d'une action gratuite.",

"THIS IS THE WAY - TELLE EST LA VOIE": "Lorsqu’une unité alliée dotée de CE mot-clé reçoit un ordre, choisissez jusqu’à X autres unités alliées HERITIERS DE LA DEATH WATCH à [RANGE 2] d’elle. Chaque unité choisie effectue, en tant qu’action gratuite, l’action indiquée par CE mot-clé de l’unité ayant reçu un ordre.",
    
"HOLD THE LINE - TENIR BON": "Tant qu'une unité dotée du mot-clé Tenir Bon est engagée, elle gagne [A_SURGE] : [HIT] et [D_SURGE] : [BLOCK].",

"EYES ON THE PRIZE : KEYWORD - TENIR LE CAP : MOT-CLE": "Tant qu'une unité dotée de CE mot-clé a son Chef d’unité à [HALF-RANGE] de 1 ou plusieurs pions Objectif ou détient 1 ou plusieurs pions Objectif, elle a le mot-clé indiqué.",
    
"TEMPTED - TENTATION": "Si une unité alliée est vaincue par une attaque ennemie et que l'unité attaquante se trouve à [RANGE 3] d'une unité dotée de CE mot-clé, une fois que l'attaque est résolue, cette unité dotée de CE mot-clé peut effectuer une action Attaquer gratuite ou un déplacement à vitesse 2 en ignorant le terrain difficile. <br>Une unité ne peut utiliser CE mot-clé qu'une fois par round.", 

"PULLING THE STRINGS - TIRER LES FICELLES": "Lorsqu'une unité utilise l'action de carte Tirer les Ficelles, choisissez une autre unité de soldats alliée à [RANGE 2]. L'unité choisie peut effectuer une action de carte gratuite ou une action Se déplacer gratuite.", 

"SHARPSHOOTER X - TIREUR D'ELITE X": "Pendant l'étape « Déterminer le couvert », une unité dotée de CE mot-clé soustrait X de la valeur numérique du couvert du défenseur. <br><i>Par exemple, une unité bénéficiant d'un couvert lourd et d'un [SUPPRESSION] qui est attaquée par une unité dotée de Tireur d'Élite 1 bénéficie d'un couvert léger.</i>", 

"MARKSMAN - TIREUR EMBUSQUE": "Après avoir converti les adrénalines d'attaque au cours de l'étape « Convertir les adrénalines d'attaque », une unité dotée de CE mot-clé peut dépenser n'importe quel nombre de [AIM]. <br>Pour chaque [AIM] ainsi dépensé, au lieu de relancer les dés, transformez un résultat vierge en résultat [HIT] ou un résultat [HIT] en résultat [CRIT], ou bien dépensez deux [AIM] pour transformer un résultat vierge en résultat [CRIT].", 

"FIRE SUPPORT - TIRS DE SOUTIEN": "Après qu'une unité dotée de CE mot-clé a reçu un ordre, elle gagne un [STANDBY].", 

"TRANSPORT": "Pendant la mise en place, une unité dotée de CE mot-clé peut choisir une unité de soldats [TROUPIER] ou [FORCE_SPECIALE] alliée à transporter. <br>Pendant l'étape « Nommer des Commandants et donner des ordres » de la Phase de Commandement du round 1, une unité dotée de CE mot-clé peut donner un ordre à l'unité choisie. <br>Si l'unité choisie n'est pas déployée lorsque l'unité dotée du mot-clé Transport se déploie, une fois que l'effet est résolu, l'unité choisie se déploie en effectuant un déplacement à vitesse 1. Commencez à mesurer le déplacement en plaçant les deux pointes d'une extrémité du gabarit de déplacement de façon qu'elles touchent toutes deux le socle de l'unité dotée de CE mot-clé. <br>Lorsque l'unité choisie se déploie de cette manière, le Chef de cette unité mesure la distance verticale parcourue pendant ce déplacement en partant de l'unité dotée du mot-clé Transport.", 

"HUNTED - TRAQUE": "Pendant la mise en place, si une ou plusieurs unités ennemies sont dotées du mot-clé Prime, chaque unité dotée de CE mot-clé gagne un pion Prime.", 

"TEAMWORK : UNIT NAME - TRAVAIL D'EQUIPE : NOM D'UNITE": "Lorsqu'une unité dotée de CE mot-clé se trouve à [RANGE 2] d'une unité alliée portant le nom spécifié par CE mot-clé, si l'une ou l'autre des unités gagne un [AIM] ou [DODGE], l'autre unité gagne un pion du même type.", 

"CLIMBING VEHICLE - VEHICULE GRIMPANT": "Une unité dotée de CE mot-clé est considérée comme une unité de soldats lorsqu'elle grimpe.", 

"QUICK THINKING - VIVACITE D'ESPRIT": "Lorsqu'une unité effectue l'action de carte Vivacité d'esprit, elle gagne 1 [AIM] et 1 [DODGE].", 

"ANTI-MATERIEL X": "Lorsqu'une unité défend contre une attaque dont la réserve d'attaque est dotée de CE mot-clé, si l'unité en défense est une unité de Véhicule, améliorez X des dés d'attaque de cette arme", 

"ANTI-PERSONNEL X": "Lorsqu'une unité défend contre une attaque dont la réserve d'attaque est dotée de CE mot-clé, si l'unité en défense est une unité de soldats, améliorez X des dés d'attaque de cette arme.", 

"AREA WEAPON - ARME A EFFET DE ZONE": "Une arme affichant une icône de [RANGE 1] jaune est une arme à effet de zone. <br>Lorsque vous utilisez une arme à effet de zone, effectuez une attaque distincte contre chaque unité, alliée et ennemie, qui se trouve en LdV et à la portée indiquée par le chiffre figurant sur l'icône de portée, même si cette unité est engagée. <br>Les attaques effectuées par des armes à effet de zone sont toujours des attaques à distance. <br>Les armes à effet de zone ne peuvent jamais être incluses dans une réserve d'attaque constituée par une unité et doivent toujours être la seule arme d'une réserve d'attaque.", 

"ARM X : CHARGE TOKEN TYPE - ARMER X : TYPE DE CHARGE": "Une unité équipée d'une carte dotée de CE mot-clé peut effectuer l'action Armer X. <br>Lorsqu'une unité effectue l'action Armer X, l'unité place X pions Charge (Avantage) du type spécifié et correspondant à la couleur du joueur qui la contrôle intégralement à [RANGE 1] et en LdV de son Chef d'unité. <br>Les pions Charge ne peuvent pas chevaucher les pions Objectif et Avantage, ni d'autres pions Charge, et ils doivent être placés complètement à plat sur une surface plane.", 

"ASSAULT X - ASSAUT X": "Lorsqu’une arme dotée de CE mot-clé est ajoutée à une réserve d’attaque, si l’unité en défense est à [RANGE 1] du Chef de l’unité attaquante, vous pouvez améliorer X dés d’attaque de cette arme.",
    
"RAM X - BELIER X": "Tant qu'une unité effectue une attaque en utilisant une réserve d'attaque qui contient une arme dotée de CE mot-clé, pendant l'étape « Modifier les dés d'attaque », elle peut changer X résultats en résultats [CRIT] si elle remplit l'une ou l'autre des conditions suivantes : <br>• Le Chef de l'unité a un socle avec encoches et l'unité a effectué au moins un déplacement normal complet à sa vitesse maximale pendant la même activation qu'une attaque utilisant Bélier X. <br>• Le Chef de l'unité a un petit socle et l'unité a effectué au moins un déplacement pendant la même activation qu'une attaque utilisant Bélier X.",

"OVERRUN X - BORDEE X": "Une unité affichant une icône de portée [00] est une arme de bordée et ne peut être utilisée que lors d'une attaque de bordée. Les attaques de bordée ne sont ni des attaques à distance ni des attaques au corps-à-corps. Une unité peut effectuer X attaques de bordée pendant son activation. Une unité possédant une arme de bordée peut effectuer une attaque de bordée après avoir effectué un déplacement normal durant lequel le gabarit de déplacement ou le socle d'au moins une de ses figurines a chevauché le socle d'une figurine ennemie. Après avoir terminé le déplacement, l'unité possédant l'arme de bordée effectue une attaque contre l'unité à travers laquelle elle s'est déplacée, en ignorant la portée pour cette attaque. Elle ne peut constituer qu'une seule réserve d'attaque lorsqu'elle effectue cette attaque et seules des armes dotées du mot-clé Bordée X peuvent être ajoutées à cette réserve d'attaque. L'arme de bordée n'est ajoutée qu'une seule fois à la réserve d'attaque, même si l'unité contient plusieurs figurines. Si une unité peut effectuer plusieurs attaques de bordée pendant son activation, elle doit effectuer un déplacement distinct à travers une unité ennemie pour chaque attaque de bordée.", 

"TOW CABLE - CABLE DE REMORQUAGE": "Après qu'un véhicule a été blessé par une réserve d'attaque qui contient une arme dotée de CE mot-clé, le joueur qui a effectué l'attaque effectue un pivot avec le véhicule qui a été blessé, puis il gagne 1 pion Immobilisation.", 

"CRITICAL X - CRITIQUE X": "Lorsqu'une unité convertit des adrénalines d'attaque pour une réserve d'attaque dotée de CE mot-clé, pendant l'étape « Convertir les adrénalines d'attaque », elle peut convertir jusqu'à X résultats [A_SURGE] en résultats [CRIT].", 

"OVERWHELM - DEBORDEMENT": "Lorsqu’une unité effectue une attaque dont la réserve contient au moins 1 arme dotée de CE mot-clé, si elle dépense au moins 1 [AIM] pendant l’étape « Relancer les dés d’attaque », l’unité en défense gagnera 1 [SUPPRESSION] lors de l’étape « Attribuer un [SUPPRESSION] au défenseur ».",
    
"BLAST - DEFLAGRATION": "Pendant l'étape « Appliquer le couvert », une unité en défense ne peut pas bénéficier de couvert léger ni de couvert lourd pour annuler des résultats [HIT] obtenus par une réserve d'attaque qui contient des dés ajoutés par une arme dotée de CE mot-clé.", 

"SCATTER - DISPERSION": "Après qu'une unité a effectué une attaque contre une unité de soldats ayant des petits socles et utilisant une réserve d'attaque qui contient une arme dotée de CE mot-clé, cette unité peut placer toute figurine de l'unité en défense autre que le Chef d'unité, en respectant les règles de cohésion, comme si le Chef de l'unité en défense venait d'effectuer un déplacement normal.", 

"CUMBERSOME - ENCOMBRANT": "Lorsqu'une unité ajoute une arme dotée de CE mot-clé à une réserve d'attaque, elle dégrade chacun des dés d'attaque de cette arme si cette unité a effectué un déplacement pendant la même activation.",

"SNIPER TEAM - EQUIPE SNIPER": "Lorsqu’une unité effectue une attaque lors de son activation, si une de ses réserves d’attaque ne contient que des armes dotées de CE mot-clé, améliorez chaque dé d’attaque de ces armes si les conditions suivantes sont vraies :<br>• L’unité n’a pas effectuée de déplacement pendant son activation.<br>• Chacune de ses figurines a une LdV vers 1 ou plusieurs figurines de l’unité en défense.<br><br>Si vous avez ainsi amélioré des dés, après l’étape « Convertir les adrénalines d’attaque » de cette réserve d’attaque, vous pouvez annuler tous les dés d’attaque de cette réserve d’attaque et passer directement à l’étape « Attribuer un [SUPPRESSION] au défenseur ». <br>Dans ce cas, si au moins 1 résultat [CRIT] a été annulé, l’unité en défense subit 1 blessure.",
    
"DETONATE X : CHARGE TYPE - EXPLOSION X : TYPE DE CHARGE": "Après qu'une unité contrôlée par n'importe quel joueur a attaqué, s'est déplacée ou a effectué une action, chaque unité possédant une arme dotée de CE mot-clé peut faire exploser jusqu'à X pions Charge (Avantage) alliés du type spécifié. <br>Lorsqu'un pion doit exploser, il explose avant toute autre capacité ou tout autre effet qui se déclenche après qu'une unité s'est déplacée ou a effectué une action, sauf en cas de dépense d'un [STANDBY], qui peut être dépensé par une unité avant que le pion n'explose. <br>Si les deux joueurs possèdent des unités qui peuvent faire exploser des pions Charge, le joueur qui ne contrôle pas l'unité venant d'effectuer l'attaque, le déplacement ou l'action peut utiliser le mot-clé Explosion X de son unité le premier. <br>Lorsqu'un pion explose, effectuez une attaque distincte contre chaque unité, alliée et ennemie, qui a une LdV sur le pion et se trouve à portée de l'arme à effet de zone, en utilisant la fenêtre de conversion d'adrénaline et les mots-clés d'arme de la carte correspondant au pion qui explose. <br>Le pion qui explose est considéré comme l'unité attaquante lorsqu'il effectue des attaques, ce qui signifie que le joueur ne peut pas dépenser de [AIM], ni modifier les dés d'attaque, quelles que soient les capacités de l'unité qui a placé le pion. <br><br>Une fois qu'un pion a explosé, retirez le du champ de bataille.", 

"FIXED : FRONT/REAR/SIDES - FIXE : AVANT/ARRIERE/FLANCS": "Pour ajouter une arme dotée de CE mot-clé à une réserve d'attaque, l'unité en défense doit comprendre au moins une figurine dont le socle se trouve partiellement à l'intérieur de l'arc de tir spécifié de la figurine attaquante.", 

"HIGH VELOCITY - HAUTE VELOCITE": "Tant qu'elle défend contre une attaque dont la réserve d'attaque ne contient que des armes dotées de CE mot-clé, l'unité en défense ne peut pas dépenser de [DODGE] pendant l'étape « Appliquer les esquives et couverts ».", 
 
"IMMOBILIZE X - IMMOBILISER X": "Une unité qui subit une ou plusieurs blessures après avoir défendu contre une attaque qui comprend une arme dotée de CE mot-clé d'arme gagne X pions Immobilisation. <br>La vitesse maximale d'une unité est réduite de 1 pour chaque pion Immobilisation qu'elle possède. <br>Une unité dont la vitesse maximale est 0 et qui possède au moins un pion Immobilisation ne peut pas effectuer de déplacements (quel qu'en soit le type). <br><br>À la fin de l'activation d'une unité, elle retire tout pion Immobilisation qu'elle possède. <br><br>Lorsqu'une unité se déplace, appliquez tout effet qui augmente sa vitesse maximale avant d'appliquer les effets qui réduisent la vitesse maximale de cette unité.",

"IMMUNE : DEFLECT - IMMUNITE : DEFLEXION": "Pendant une attaque, si la réserve d'attaque contient des armes dotées de CE mot-clé, l'unité attaquante ne peut pas subir de blessures dues au mot-clé Déflexion.", 

"IMPACT X": "Pendant l'étape « Modifier les dés d'attaque », si l'unité en défense est dotée du mot-clé Armure ou Armure X, une unité dont la réserve d'attaque contient une arme dotée de CE mot-clé peut changer jusqu'à X résultats [HIT] en résultats [CRIT] pour cette attaque.", 

"ION X": "Une unité de véhicule ou de soldats droïdes qui subit des blessures après avoir défendu contre une attaque comprenant une arme dotée de CE mot-clé gagne X pions Ionique. <br><br>Au début de l'activation d'une unité, lancez un dé de défense blanc pour chaque pion Ionique que possède l'unité. <br>Si vous obtenez des résultats vierges, cette unité effectue une action de moins pendant son activation. <br><br>À la fin de l'activation d'une unité, elle retire tout pion Ionique qu'elle possède. <br><br>Si une réserve d'attaque est dotée du mot-clé Ion X, au début de l'étape « Modifier les dés d'attaque » de la séquence d'attaque, avant tout autre effet, l'unité en défense doit retourner des pions Bouclier actifs, si possible, pour chaque résultat [HIT] et [CRIT] du jet d'attaque, jusqu'à X.", 

"LETHAL X - LETAL X": "Lorsqu'une unité effectue une attaque dont la réserve contient une arme dotée de CE mot-clé, elle peut dépenser jusqu'à X [AIM] pendant l'étape « Modifier les dés d'attaque ». <br>Dans ce cas, la réserve d'attaque gagne Perforant 1 pour chaque [AIM] dépensé. <br><br>L'unité attaquante ne peut pas relancer de dés grâce aux [AIM] ainsi dépensés.", 

"LONG SHOT - LONGUE DISTANCE": "Lorsqu'une unité possédant au moins une arme dotée de CE mot-clé effectue une attaque, avant de choisir une unité ennemie à attaquer pendant l'étape « Déclarer le défenseur », cette unité peut dépenser un [AIM] pour améliorer de 1 la portée maximale de chaque arme ayant CE mot-clé jusqu'à la fin de la séquence d'attaque. <br><br>L'unité attaquante ne peut pas relancer de dés grâce aux [AIM] ainsi dépensés. <br><br>Un seul [AIM] peut-être ainsi dépensé par séquence d'attaque.", 

"PIERCE X - PERFORANT X": "Si une unité attaque avec une arme dotée de CE mot-clé, elle peut annuler jusqu'à X résultats [BLOCK] pendant l'étape « Modifier les dés de défense ». <br>CE mot-clé peut être utilisé pour annuler des résultats [BLOCK] de dés de défense lancés par une unité utilisant le mot-clé Gardien X. Dans ce cas, traitez les résultats [BLOCK] annulés comme des résultats vierges. Après avoir utilisé CE mot-clé de cette manière, toute valeur inutilisée de Perforant X peut toujours être utilisée pour annuler des résultats [BLOCK] obtenus par le défenseur. <br><i>Par exemple, une unité dotée du mot-clé Perforant 3 attaque une unité ennemie, et une autre unité ennemie utilise Gardien 2 pour annuler 2 résultats [HIT]. Après avoir converti les résultats [D_SURGE], l'unité utilisant le mot-clé Gardien a obtenu 2 résultats [BLOCK]. L'unité attaquante utilise Perforant pour annuler les 2 résultats [BLOCK] et l'unité utilisant Gardien subit 2 blessures. Le défenseur lance alors les dés de défense et l'unité attaquante peut annuler 1 résultat [BLOCK] de plus obtenu par le défenseur puisqu'elle n'a utilisé que 2 points sur les 3 accordés par son mot-clé Perforant 3.</i>", 

"POISON X": "Une unité de soldats non-droïdes qui subit des blessures provoquées par une réserve d'attaque contenant une arme dotée de CE mot-clé gagne X pions Poison. <br>À la fin de l'activation d'une unité, elle subit une blessure pour chaque pion Poison qu'elle possède, puis elle retire tous ses pions Poison.", 

"VERSATILE - POLYVALENT": "Certaines armes à distance sont dotées de CE mot-clé. Une unité peut effectuer une attaque à distance en utilisant une arme dotée de CE mot-clé même si elle est engagée. <br>Une arme dotée de CE mot-clé qui est à la fois une arme de corps-à-corps et à distance peut être utilisée pour effectuer soit une attaque au corps-à-corps soit une attaque à distance.",  

"PRIMITIVE - PRIMITIF": "Pendant l'étape « Modifier les dés d'attaque », après avoir résolu tous les points du mot-clé Impact X, si l'unité en défense est dotée du mot-clé Armure ou Armure X, une unité dont la réserve d'attaque contient une arme dotée de CE mot-clé doit changer tous ses résultats [CRIT] en résultats [HIT] pour cette attaque.", 

"BEAM X - RAYONS X": "Pendant l'étape « Déclarer un défenseur supplémentaire », si la réserve d'attaque d'une unité contient une arme dotée de CE mot-clé, cette unité peut déclarer jusqu'à X attaques supplémentaires en constituant des réserves d'attaque n'utilisant que l'arme dotée de CE mot-clé, même si l'arme a déjà été ajoutée à une réserve d'attaque. <br>Ces attaques supplémentaires ne génèrent pas d'autres attaques. <br>Chaque attaque supplémentaire doit cibler une unité en défense différente qui se trouve à [RANG 1] de la dernière unité déclarée en défense. <br>Ces attaques supplémentaires doivent être en LdV de l'unité attaquante mais peuvent se trouver au-delà de la portée maximale de l'arme dotée de CE mot-clé. <br><br>Les unités ne peuvent pas utiliser les mots-clés Rayons X et Pistolero au cours de la même attaque.", 

"SPRAY - SOUFFLE": "Lorsqu'une figurine ajoute une arme dotée de CE mot-clé à la réserve d'attaque, cette arme fait contribuer ses dés un nombre de fois égal au nombre de figurines de l'unité en défense qui sont en LdV de la figurine utilisant cette arme. <br><i>Par exemple, si un TL-TT attaque une unité de 3 Death Troopers avec un lance-flamme, comme le lance-flamme est doté du motclé Souffle et dispose de 2 dés noirs, le lance-flamme ajoute 6 dés d'attaque noirs à la réserve d'attaque.</i>", 

"SUPPRESSIVE - SUPPRESSIF": "Après avoir défendu contre une réserve d'attaque qui contient une arme dotée de CE mot-clé, l'unité en défense gagne un [SUPPRESSION] pendant l'étape « Attribuer un [SUPPRESSION] au défenseur ».", 

"SIDEARM MELEE/RANGE - ARME DE POING : CORPS-A-CORPS/A DISTANCE": "Si une amélioration qui ajoute une figurine à une unité est dotée du mot-clé Arme de Poing : corps-à-corps, la figurine ajoutée par cette amélioration ne peut pas ajouter à une réserve d'attaque des armes de corps-à-corps autres que celles indiquées sur la carte Amélioration dotée du mot-clé Arme de Poing : corps-à-corps. <br>Si une amélioration qui ajoute une figurine à une unité est dotée du mot-clé Arme de Poing : à distance, la figurine ajoutée par cette amélioration ne peut pas ajouter à une réserve d'attaque des armes à distance autres que celles indiquées sur la carte Amélioration dotée du mot-clé Arme de Poing : à distance. <br><i>Par exemple, la carte Amélioration « Garde avec Bâton Statique » fournit une arme de corps-à-corps et le mot-clé Arme de Poing : corps-à-corps. La figurine ajoutée par cette amélioration ne peut utiliser que l'arme indiquée sur l'amélioration « Garde avec Bâton Statique » pendant une attaque au corps-à-corps. <br>Cette figurine peut toujours utiliser n'importe quelle arme à distance disponible, telle que l'arme à distance indiquée sur la carte Unité « Gardes Royaux de l'Empereur », pendant une attaque à distance.</i>", 

"LEADER - CHEF": "Une figurine dotée de CE mot-clé est considérée comme le Chef d'une unité pour tous les effets de jeu et capacités. <br>Si une figurine dotée du mot-clé Chef ayant un seuil de blessure de 2 est vaincue alors qu'elle se trouve dans une unité ayant un seuil de blessure de 1, remplacez normalement une des figurines restantes de cette unité, puis attribuez un pion Blessure à la figurine dotée de CE mot-clé. <br><br>Chaque unité ne peut s'équiper que d'une seule carte Amélioration dotée de CE mot-clé.", 

"CYCLE": "À la fin de l'activation d'une unité, redressez chacune de ses cartes Amélioration inclinées dotées de CE mot-clé qui n'a pas été utilisée pendant cette activation. <br>Seules l'utilisation de l'arme, des mots-clés ou d'un autre texte de la carte sont considérées comme utiliser cette carte Amélioration.", 

"DIVULGE - DIVULGATION": "Certaines cartes Commandement sont dotées de CE mot-clé : elles sont alors divisées par une ligne horizontale, qui sert à séparer visuellement l'effet de CE mot-clé de l'effet normal de la carte Commandement. <br>Certaines de ces cartes Commandement disposent de plusieurs options : le joueur doit alors en choisir une. <br>Ces cartes peuvent être révélées au début de la phase ou étape indiquée par CE mot-clé. Si une carte est révélée de cette manière, résolvez le texte qui suit CE mot-clé. <br>Une carte ainsi révélée n'est pas jouée : elle est remise dans la main de Commandement de ce joueur à la fin de l'étape au cours de laquelle elle a été divulguée. Si une carte qui a le mot-clé Permanent est divulguée, elle n’est pas remise dans la main de Commandement, mais reste en jeu. <br>Les joueurs peuvent divulguer autant de cartes Commandement qu'ils le souhaitent. <br>Si les deux joueurs disposent de cartes Commandement qui doivent être divulguées en même temps, le joueur bleu peut révéler la sienne le premier. S'il décline cette opportunité, la carte ne peut plus être divulguée.", 

"NONCOMBATTANT - NON-COMBATTANT": "Une figurine dotée de CE mot-clé ne peut pas ajouter d'armes aux réserves d'attaque, et les blessures doivent être attribuées à des figurines autres que des Chefs d'unité n'étant pas dotées du mot-clé Non-combattant, si possible. <br>Si une figurine dotée de CE mot-clé possède déjà un ou plusieurs pions Blessure, elle doit se voir attribuer des blessures avant les figurines qui ne possèdent pas de pions Blessure. <br>Si la figurine de Chef d'unité d'une unité dotée du mot-clé Non-combattant est vaincue, une figurine Non-combattante ne peut pas être remplacée par une nouvelle figurine de Chef d'unité sauf s'il n'y a pas d'autres figurines n'étant pas dotées du mot-clé Non-combattant.",

"PERMANENT": "Certaines cartes Commandement sont dotées de CE mot-clé. Contrairement aux cartes Commandement ordinaires, ces cartes ne sont pas défaussées pendant la Phase Finale et leurs effets persistent tant qu'elles sont en jeu.", 

"SMALL - PETIT": "Une unité comprenant 1 ou plusieurs figurines ALTER EGO dotées de CE mot-clé ne peut pas être ciblée par des attaques si le Chef de l'unité attaquante n'a une LdV que vers la figurine Alter Ego dotée du mot-clé Petit.", 

"BANE TOKENS - PIONS BANE": "Cad Bane dispose de trois pions Bane uniques qu'il peut placer sur le champ de bataille. Les pions Bane sont recto verso : un côté uniformisé (face cachée) et un côté comportant une image parmi trois différentes, chacune déclenchant un effet unique (face visible). Les pions Bane doivent être placés face cachée sur le champ de bataille et ils ne peuvent pas chevaucher de pions Objectif et Avantage. Les pions Bane sont des effets ennemis et chaque joueur ne peut posséder qu'un exemplaire de chaque pion Bane sur le champ de bataille à la fois. Lorsqu'une figurine ennemie se déplace, se déploie ou est placée à [RANGE 1] d'un pion Bane ennemi, si cette figurine a une LdV vers le pion, ce dernier est révélé. Les figurines peuvent se déplacer à travers les pions Bane, mais pas les chevaucher. Lorsqu'un pion Bane est révélé, il a l'un des effets suivants : <br>Me voilà : si Cad Bane ne se trouve pas sur le champ de bataille et n'est pas vaincu, son pion Me voilà est remplacé par sa figurine. Ensuite, Cad Bane se donne un ordre à lui-même. <br> • Si Cad Bane se trouve sur le champ de bataille, son pion Me voilà est remplacé par sa figurine. Tout pion attribué à Cad Bane lui reste attribué. <br> • Si Cad Bane est vaincu, retirez ce pion. <br> • Au début de chaque round, en commençant par le joueur bleu, un joueur peut révéler un pion Me voilà allié et résoudre ses effets. <br>Fumée et miroir : le pion est retiré. <br>Kablamo ! : le pion explose en utilisant le profil d'arme indiqué sur la carte Commandement de Cad Bane « Je Fixe les Règles à Présent ». Ensuite, le pion est retiré.", 

"GRAFFITI TOKENS - PIONS GRAFFITI": "Un pion Graffiti (Avantage) représente une image ou un signe au fort pouvoir symbolique tagué sur le terrain du champ de bataille. Les pions Graffiti ont un effet sur le moral d'une unité, ils sont recto verso et doivent être placés à plat avec comme face visible la couleur correspondant au joueur les contrôlant. <br>Pendant l'étape « Se rallier » de l'activation d'une unité, elle peut lancer un dé supplémentaire si elle a une LdV vers et se trouve à [RANGE 2] d'un pion Graffiti placé par une figurine alliée. <br>Elle doit lancer un dé de moins (jusqu'à un minimum de 1 dé) si elle a une LdV et se trouve à [RANGE 2] d'un pion Graffiti placé par une figurine ennemie. <br><br>Les pions Graffiti restent en jeu jusqu'à la fin de la partie. <br><br>Les unités peuvent se déplacer au travers des pions Graffiti et terminer leurs déplacements en chevauchant ces derniers.", 

"RECONFIGURE - RECONFIGURATION": "Lorsqu'une unité équipée d'une carte Amélioration dotée de CE mot-clé récupère ou effectue une action Récupérer, le joueur qui contrôle cette unité peut retourner cette carte Amélioration sur son autre face en plus de tout effet lié à la récupération. Si une carte Amélioration affiche l'icône Incliner, utiliser la capacité Reconfiguration ne provoque pas l'inclinaison de cette carte Amélioration.",

"REPAIR X / CAPACITY Y - REPARATION X : CAPACITE Y": "Lorsqu'une unité utilise l'action de carte Réparation X : Capacité Y, choisissez une unité de soldats droïdes ou de véhicule alliée à [RANGE 1] et en LdV et placez un pion Blessure sur la carte dotée de CE mot-clé. <br>Retirez au total jusqu'à X pions Blessure, Ionique et/ou Dégât de véhicule de l'unité choisie ou restaurez jusqu'à X figurines de cette unité. <br>Cette capacité ne peut pas être utilisée si la carte dotée de CE mot-clé possède sur elle un nombre de pions Blessure supérieur ou égal à Y. <br>Les pions Blessure placés sur des cartes ne sont pas considérés comme possédés par des unités et ne comptent pas dans le seuil de blessure de cette unité. Ils ne peuvent pas non plus être retirés par des capacités qui retirent des pions Blessure à des unités. <br>Si une unité dispose de plusieurs capacités Réparation X : Capacité Y, considérez chaque mot-clé comme une capacité à part. <br><br>De plus, chaque action est considérée comme unique, et une unité qui a accès à plusieurs d'entre elles ne peut utiliser chaque capacité qu'une seule fois au cours de son activation. <br>Cette règle s'applique même si l'unité a accès à deux capacités identiques de différentes sources.",

"RESTORE - RESTAURATION": "Certaines capacités, comme les mots clés Traiter et Réparation, de même que certains effets de carte, permettent à un joueur de restaurer des figurines dans des unités alliées. <br>Pour restaurer une figurine dans une unité, une ou plusieurs figurines de cette unité doivent avoir été vaincues ce round. <br>Choisissez une figurine qui a été vaincue pendant le round en cours et placez cette figurine sur le champ de bataille en cohésion avec son Chef d'unité. <br>Ensuite, donnez à cette figurine un nombre de pions Blessure égal au seuil de blessure indiqué sur sa carte Unité ou Amélioration moins un.",

"TREAT X / CAPACITY Y - TRAITER X : CAPACITE Y": "Lorsqu'une unité utilise l'action de carte Traiter X : Capacité Y, choisissez une unité de soldats non-droïdes alliée à [RANGE 1] et en LdV et placez un pion Blessure sur la carte dotée de CE mot-clé. <br>Retirez au total jusqu'à X pions Blessure et/ou Poison de l'unité choisie ou restaurez jusqu'à X figurines dans cette unité. <br>Cette capacité ne peut pas être utilisée si la carte dotée de CE mot-clé possède sur elle un nombre de pions Blessure supérieur ou égal à Y. <br>Les pions Blessure placés sur des cartes ne sont pas considérés comme possédés par des unités et ne comptent pas dans le seuil de blessure de cette unité. Ils ne peuvent pas non plus être retirés par des capacités qui retirent des pions Blessure à des unités. <br>Si une unité dispose de plusieurs capacités Traiter X : Capacité Y, considérez chaque mot-clé comme une capacité à part. <br><br>De plus, chaque action est considérée comme unique, et une unité qui a accès à plusieurs d'entre elles ne peut utiliser chaque capacité qu'une seule fois au cours de son activation. Cette règle s'applique même si l'unité a accès à deux capacités identiques de différentes sources."

};
